spring.application.name=SaveCar

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Cria e atualiza tabelas no banco automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostrar injeções SQL no terminal
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# Flyway Configurações

# Desativo por agora
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migrations
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true

spring.jwt.expiration=${JWT_EXPIRATION}
spring.jwt.key=${JWT_KEY}